name: Frontend CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      - name: Stylesheet check
        run: echo 'stylesheet check'

      - name: Build image
        run: docker build -t pcts-front .

      - name: Build yarn
        run: docker run pcts-front yarn build

      - name: Run tests
        run: docker run --volume ${PWD}/:/app pcts-front bash -c "CI=false yarn coverage"

      - name: SonarCloud Report coverage
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    needs: integration
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME_DEV: ${{ 'pcts-frontend-dev' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        run: |
          heroku container:login
          heroku container:push web -a $HEROKU_APP_NAME_DEV
          heroku container:release web -a $HEROKU_APP_NAME_DEV

  deploy_main:
    if: github.ref == 'refs/heads/main'
    needs: integration
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME_PROD: ${{ 'pcts-frontend-prod' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        run: |
          heroku container:login
          heroku container:push web -a $HEROKU_APP_NAME_PROD
          heroku container:release web -a $HEROKU_APP_NAME_PROD

  # deploy_dev:
  #   if: github.ref == 'refs/heads/dev'
  #   needs: integration
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Deploy to Staging
  #       id: deploy-vercel-staging
  #       uses: amondnet/vercel-action@v20
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  #         scope: ${{ secrets.VERCEL_ORG_ID }}

  # deploy_main:
  #   if: github.ref == 'refs/heads/main'
  #   needs: integration
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Deploy to Production
  #       uses: amondnet/vercel-action@v20
  #       id: deploy-vercel-production
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  #         vercel-args: '--prod'
  #         scope: ${{ secrets.VERCEL_ORG_ID }}
